### ISSUE TITLE
Buggy Picture In Picture Mode 0.11.0

### ISSUE THREAD

**Issue by MrGizmo757** [4gray/iptvnator#167]
Since i updated to version 0.11.0  when i go into Picture In Picture mode, when my mouse cursor passes over the video window, the entire window turns red. This happens with both the HTML5 player and jsplayer modes. This problem is also present on Windows 10 ( .exe ) and Debian Linux ( Snap Package ) also present on different sets of hardware. I attached a screenshot. 
![Screenshot (28)](https://user-images.githubusercontent.com/10471547/192124285-86041c46-5ded-4197-b9db-60385252a76c.png)

**Comment by kuehhe1** [comment]
Hello,
the same problem of the "red" picture in picture window also exists on LinuxMint 21 Cinnamon.
Sometimes it remains "red" even if the mouse is removed from the small window or the application window is minimized to the bar. The state can be terminated by single or double clicking in the "red" colored picture in picture window. The mode is then terminated and the TV picture is displayed again in the application window. Is the "red" coloring of the picture in picture window now a feature or bug? 

Translated with www.DeepL.com/Translator (free version)

**Comment by 4gray** [comment]
This is a bug in electron, see: https://github.com/electron/electron/issues/35205 & https://github.com/electron/electron/issues/34406 
Just tried to update the electron version locally to v20.2.0 the PIP window looks fine there. I will release a new version in the next few days with a hotfix. 
Thanks for testing and your feedback! 🚀

**Comment by kuehhe1** [comment]
Thank you for your supportive response.
I found two more bugs, can I show them here in the topic or is a separate issue required for each bug?

**Comment by 4gray** [comment]
@kuehhe1 Yes, this can be because the icons are loaded from different sources. In the channel list directly from the playlist and in the epg respectively from the xml file with epg.

> I found another one bugs, can I show them here in the topic or is a separate issue required for each bug?

If you have more, please create new issue(s).

**Comment by kuehhe1** [comment]
Thank you very much.
this is the EPG entered in IPTVnator Source: https://a1.epg.wb1.xyz/

and the first line of my *.m3u file looks like this:
```
#EXTM3U
#EXTINF:-1 tvg-name="Das Erste HD" group-title="GERMAN TV" tvg-logo="http://logos.zattic.com/images/channels/logos/2a2a4aee64bbd6f7f817/black/84x48.png" tvg-id="ARD.de",Das Erste HD
https://mcdn.daserste.de/daserste/de/master.m3u8
```

If this were to cause problems, I would have to replace or adjust the entry for: `logo="http://logos.zattic.com/images/channels/logos/2a2a4aee64bbd6f7f817/black/84x48.png"`
with the logo specification:
`icon src="https://epggw.a1.net/img/station/darkbg/200x200/1.png" in my *.m3u.`

Otherwise, there are currently no further problems.

**Comment by 4gray** [comment]
@kuehhe1 thank you for your feedback!

The icon in your playlist looks correct, it's the channel icon which is displayed in the channel overview. But if you look in your EPG source ([a1.epg.wb1.xyz/](https://a1.epg.wb1.xyz/)) for "Das Erste HD", there is just this icon in the form of a radio tower (https://epggw.a1.net/img/station/darkbg/200x200/20131.png) and it's visible in the multi-epg list.
![image](https://user-images.githubusercontent.com/1503032/192865585-107a3f0f-a0f1-473c-9dbc-40ad382f9531.png)

As a feature in IPTVnator, it would be a good idea to somehow collect all icons in the application and display available icons in all lists/overview, but this is a task for the future :-)

**Comment by kuehhe1** [comment]
Hello, short feedback of my problem solution. 
Due to some stream problems IPTVnator 0.11.0 didn't want to play anymore I uninstalled IPTVnator 0.11.0, renamed the old config directory to: ~/.config/iptvnator.old.
After subsequent IPTVnator 0.11.0 reinstallation, adding my *.m3u lists and the four (4) EPG sources: 
https://iptv-org.github.io/epg/guides/de/horizon.tv.epg.xml.gz
https://iptv-org.github.io/epg/guides/de/hd-plus.de.epg.xml.gz
https://iptv-org.github.io/epg/guides/at/magentatv.at.epg.xml.gz
https://iptv-org.github.io/epg/guides/at/tvheute.at.epg.xml.gz

Now also the problematic streams work with picture and sound, as well as the EPG and Multi-EPG. The EPG source: https://a1.epg.wb1.xyz/ I had to remove because it creates a conflict with the others regarding the Multi-EPG.

The problem of the small red picture in picture still exists, but a solution to this was previously announced.  Many Thanks and best regards.

**Comment by 4gray** [comment]
@kuehhe1 glad to hear that :-) 
Released a new version v0.11.1, this should fix the red background problem in PIP mode (tested on mac os), see: https://github.com/4gray/iptvnator/releases/tag/v0.11.1

**Comment by kuehhe1** [comment]
Thank you, the new version is just reported.
![iptvnator_Update-auf-0 11 1](https://user-images.githubusercontent.com/45901795/193447903-d032036d-fb15-4cdd-a90c-93550a556b44.png)

**Comment by MrGizmo757** [comment]
Yep. Fixed for me too. Thanks. :)
