### ISSUE TITLE
Impossible to play Iptv playlist in web application PWA

### ISSUE THREAD

**Issue by trimechee** [4gray/iptvnator#218]
Hello, I read the changelog 
"PWA 📱
IPTVnator is now available as a [web-application](https://iptvnator.vercel.app/), which means that you can use it directly from the browser. This means that application can be run on smartphones, tablets, set-top boxes or smart tv browsers."

so i tried to play my iptv playlist with the PWA web application but it doesn't work, and i install IPTVnator in windows 10and i play the same iptv m3u8 playlist and it succeeded, i can play this iptv playlist, i tried the web application in firefox, edge and it fails but succeded in executable application for windos 10,  this is the playlist :  https: //i.mjh.nz/PlutoTV/fr.m3u8

**Comment by bendschs** [comment]
same here, the backend seems to start up correctly but does not get any feedback from the front when your try to play something.

**Comment by trimechee** [comment]
But when I install IPTVnator windows version in my notebook, there is no problem, may be web browsers doesn't accept iptv connecions....

**Comment by bendschs** [comment]
same here, same m3u is working in the electron wrapper.
for me the front-end seems to be working fine (except i can only upload m3u via file, not via link).

**Comment by 4gray** [comment]
In the playlist above, the streams are hosted at `http://` addresses and not `https://`. Since the PWA application is deployed in an https context, the browser does not allow to get content from non-https. Details: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

A self-hosted solution running by default on `http://localhost:...` will solve this issue as well as the electron application.

**Comment by trimechee** [comment]
Great ! Thank you very much for your precious help 🥇 

I went  read the instructions to install self-hosted PWA but I am not an expert, I did not understand very well what should I do, I do not see an application to install, should I use cmd command line and put these 2 commands without installing anything else? can we use self-hosted PWA on a computer or smart tv therefore there is no need any more to install iptv player or android iptv application for smart tv ? thank you !

$ cd docker
$ docker-compose up -d

https://github.com/4gray/iptvnator/tree/electron/docker

**Comment by 4gray** [comment]
You are welcome :-)

You need to have docker installed so that you can run the containers. But in general, this is just another way to run iptvnator as web-application on your device.

For android or smart tv you can still use https://iptvnator.vercel.app/. But if you install it on your device you can e.g. bypass the limit on adding large files by url and issues with mixed content (http/https).

**Comment by trimechee** [comment]
Great !! Thank you very much for your big precious help :) 🥇
