### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by dxD7** [4gray/iptvnator#64]
Program was working perfectly fine for awhile, best one I've used so far, then suddenly I get this error every time I start it and it can't keep saved playlist after closing the program.
(W10 Version 10.0.19042 Build 19042)
![Screenshot 2021-06-18 043439](https://user-images.githubusercontent.com/40486657/122628976-968e4280-d087-11eb-9048-98e5212a6199.png)

**Comment by 4gray** [comment]
Thank you for the feedback!
Could you please open dev tools in the app (available from the  "Help" menu) and check whether the are some other errors visible?

**Comment by dxD7** [comment]
![Screenshot 2021-06-19 171213](https://user-images.githubusercontent.com/40486657/122655638-ea4d6a00-d121-11eb-8132-8c7936ff73d5.png)

**Comment by 4gray** [comment]
@dxD7 It looks fine, nothing critical. 

It would be interesting to see the content of the console during the error from the first screenshot. Or does it occur before the application opens? 

I have another small suspicion of a corrupted database file (data.db), which is used to store playlists. You could try deleting the file in order to recreate it.

**Comment by dxD7** [comment]
@4gray Well thank you very much I found the data.db file and deleted it, its now fixed.
